export const links = [
  {
    name: 'Home',
    hash: '#home',
    href: '/',
  },
  {
    name: 'Shop',
    hash: '#shop',
    href: '/shop?categories=&strainType=&brands=',
  },
]

export const categories = [
  { name: 'All categories', icon: '/images/categories.png' },
  { name: 'Accessories', icon: '/images/accessories.png' },
  { name: 'Concentrates', icon: '/images/acid.png' },
  { name: 'Edibles', icon: '/images/categories.png' },
  { name: 'Flower', icon: '/images/flower.png' },
  { name: 'Tinctures', icon: '/images/dose.png' },
  { name: 'Topicals', icon: '/images/categories.png' },
]

export const strainType = ['Hybrid', 'Indica', 'Sativa']

export const brands = [
  '1Lyfe',
  'AbsoluteXtracts',
  'Alive & Well',
  'Bear Labs',
  'Bhang',
  'Big Chief Extracts',
  'Biohazard',
  'Brio',
  'Cann',
  'Cannabiotix',
  'Cannavis',
  'Canndescent',
  'Chill - Caliva',
  'Claybourne Co.',
  'Deep Sea',
  'Deli Greens',
  "Dr. Norm's",
  'Ember Valley',
  'Empire',
  'FloraCal Farms',
  'Fun Uncle',
  'Fuzzies',
  'Gold Flora',
  'Herb & Zen',
  'Honeyleaf',
  'House Party',
  'Hush',
  'Jeeters',
  'Jetpacks',
  'Jetty Extracts',
  'Kahna',
  'Karma',
  'King Palms',
  'Kurvana',
  'Left Coast',
  'Legion Of Bloom',
  'Lolo',
  'Malibu Gold',
  'Mota',
  'Moxie',
  'Nativ',
  'Papa & Barkley',
  'Punch',
  'Rollers Delight',
  'Rove',
  'Select',
  'Stiiizy',
  'THC Living',
  'Tonik',
  'West Coast Cure',
  'WonderBrett',
  'Yummi Karma',
  'Z Wave Distro',
]
