export const links = [
  {
    name: 'Home',
    hash: '#home',
    href: '/',
  },
  {
    name: 'Shop',
    hash: '#shop',
    href: '/shop',
  },
]

export const categeories = [
  'All categories',
  'Accessories',
  'Concentrates',
  'Edibles',
  'Flower',
  'Tinctures',
  'Topicals',
]

export const strainType = ['Hybrid, Indica, Sativa']

export const brands = [
  '1Lyfe',
  'AbsoluteXtracts',
  'Alive & Well',
  'Bear Labs',
  'Bhang',
  'Big Chief Extracts',
  'Biohazard',
  'Brio',
  'Cann',
  'Cannabiotix',
  'Cannavis',
  'Canndescent',
  'Chill - Caliva',
  'Claybourne Co.',
  'Deep Sea',
  'Deli Greens',
  "Dr. Norm's",
  'Ember Valley',
  'Empire',
  'FloraCal Farms',
  'Fun Uncle',
  'Fuzzies',
  'Gold Flora',
  'Herb & Zen',
  'Honeyleaf',
  'House Party',
  'Hush',
  'Jeeters',
  'Jetpacks',
  'Jetty Extracts',
  'Kahna',
  'Karma',
  'King Palms',
  'Kurvana',
  'Left Coast',
  'Legion Of Bloom',
  'Lolo',
  'Malibu Gold',
  'Mota',
  'Moxie',
  'Nativ',
  'Papa & Barkley',
  'Punch',
  'Rollers Delight',
  'Rove',
  'Select',
  'Stiiizy',
  'THC Living',
  'Tonik',
  'West Coast Cure',
  'WonderBrett',
  'Yummi Karma',
  'Z Wave Distro',
]
